<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.*">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="BepInEx.Core" Version="5.4.21" />

		<PackageReference Include="Goorakh-Quality" Version="0.7.8" Publicize="true" />

		<PackageReference Include="MonoDetour" Version="0.7.15" />

		<PackageReference Include="MonoDetour.HookGen" Version="0.7.14" />

		<PackageReference Include="R2API.Items" Version="1.0.*" />
		<PackageReference Include="R2API.Language" Version="1.0.*" />
		<PackageReference Include="R2API.Animations" Version="1.2.1" />
		<PackageReference Include="R2API.Prefab" Version="1.1.1" />
		<PackageReference Include="R2API.RecalculateStats" Version="1.6.6" />
		<PackageReference Include="Rune580.Mods.RiskOfRain2.RiskOfOptions" Version="2.8.5" />
		<PackageReference Include="score-MiscFixes" Version="1.5.9" />

		<PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.1.0-r.0" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.12.9" NoWarn="NU1701" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="HalcyonFixes">
	    <HintPath>..\..\references\HalcyonFixes.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<!-- Window Build -->
		<!-- <Exec Command="xcopy /Y /s /e &quot;$(TargetPath)&quot; &quot;$(ProjectDir)..\Thunderstore\plugins&quot;&#xD;&#xA;&#xD;&#xA;" />
		<Exec Command="rmdir /S /Q &quot;C:\Users\TIZIA\AppData\Roaming\com.kesomannen.gale\riskofrain2\profiles\modding\BepInEx\plugins\0n_x-testmod&quot;&#xD;&#xA;&#xD;&#xA;" />
		<Exec Command="mkdir &quot;C:\Users\TIZIA\AppData\Roaming\com.kesomannen.gale\riskofrain2\profiles\modding\BepInEx\plugins\0n_x-testmod&quot;&#xD;&#xA;&#xD;&#xA;" />
		<Exec Command="xcopy /Y /s /e &quot;$(ProjectDir)..\Thunderstore\plugins&quot; &quot;C:\Users\TIZIA\AppData\Roaming\com.kesomannen.gale\riskofrain2\profiles\modding\BepInEx\plugins\0n_x-testmod&quot;" /> -->
		
		<!-- Linux Build -->
		<Exec Command="rsync -avz $(TargetPath) $(ProjectDir)../Thunderstore/plugins" />
		<Exec Command="rm -rf /home/tizian/.local/share/com.kesomannen.gale/riskofrain2/profiles/Modding/BepInEx/plugins/0n_x-testmod" />
		<Exec Command="mkdir /home/tizian/.local/share/com.kesomannen.gale/riskofrain2/profiles/Modding/BepInEx/plugins/0n_x-testmod" />
		<Exec Command="rsync -avz $(ProjectDir)../Thunderstore /home/tizian/.local/share/com.kesomannen.gale/riskofrain2/profiles/Modding/BepInEx/plugins/0n_x-testmod" />
	</Target>
</Project>